film
MaxxximL/java-filmorate pull request #1
Opened 2024-11-25 20:32 UTC by MaxxximL

2024-11-26 18:27 UTC, andrew-larkin requested changes
Привет! Отличный старт! Остается разобраться с ломбоковскими аннотациями и можно будет двигаться дальше.

2024-11-26 18:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public int getId() {
не нужны, т.к. у тебя используются @Getter и @Setter над классом

2024-11-26 18:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
@Data уже содержит большую часть аннотаций, указанных ниже. поэтому тебе нужно посмотреть и избавиться от лишнего

2024-11-26 18:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String testName;
не должно фигурировать test' в названии переменных

2024-11-26 18:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@ToString
правки аналогичны классу Film

2024-11-26 18:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/ValidationException.java
> +public class ValidationException extends RuntimeException {
можно поместить в папку exception

2024-11-28 22:02 UTC, andrew-larkin requested changes
Привет! Нашел твою проблему - сильно много зависимостей напихал в pom.xml. Убери их, плюс поменяй импорты для @Valid. Приложение запускается таким образом.

2024-11-28 22:02 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import javax.validation.Valid;
никакого javax, должна быть jakarta

2024-11-28 22:02 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +import javax.validation.Valid;
аналогично FilmController

2024-11-28 22:02 UTC, andrew-larkin commented on pom.xml
> +		<dependency>
удаляем все со строки 53 до 93

2024-11-30 12:08 UTC, MaxxximL commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import javax.validation.Valid;
Спасибо!!! Работает
Я понял, нельзя импортировать все подряд зависимости )

2024-12-10 22:22 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-12-17 18:49 UTC, merged